/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2021-01-05 06:24:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.commonCode;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class commonCodeInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<h1>자유게시판</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"width:650px;\" align=\"right\">\r\n");
      out.write("\t\t<a href=\"./commonCode.ino\">리스트로</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr style=\"width: 600px\">\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"./commonCodeInsert.ino\">\r\n");
      out.write("\t\t<div style=\"width: 150px; float: left;\">코드 :</div>\r\n");
      out.write("\t\t<div style=\"width: 500px; float: left;\" align=\"left\"><input type=\"text\" name=\"name\"/></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div style=\"width: 150px; float: left;\">코드명 :</div>\r\n");
      out.write("\t\t<div style=\"width: 500px; float: left;\" align=\"left\"><input type=\"text\" name=\"title\"/></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div style=\"width: 150px; float: left;\">사용유무(라디오버튼):</div>\r\n");
      out.write("\t\t<div style=\"width: 500px; float: left;\" align=\"left\"><input type=\"radio\"> </div>\r\n");
      out.write("\t\t<div align=\"right\">\r\n");
      out.write("\t\t<input type=\"submit\" value=\"등록\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"다시쓰기\" onclick=\"reset()\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"취소\" onclick=\"location.href='./commonCode.ino'\">\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
